Linear Algebra Problem Set

Problem 1:

I ran the below code to get a random set of $ \mathbb{Z}^4 $ matrices limiting the output to 1 to 5, then I copied the result into variables in case the randomizer got run again.  I worked off that set.

In [18]:
import numpy as np
import numpy.matlib

i4_matrices = []
for x in range(2):
    i4_matrices.append(np.matlib.mat(np.random.randint(1, 6, size=(4, 4))))

i4_matrices

[matrix([[4, 1, 5, 4],
         [5, 3, 3, 3],
         [5, 3, 1, 5],
         [5, 4, 2, 1]]),
 matrix([[4, 2, 4, 4],
         [5, 4, 2, 2],
         [1, 1, 2, 3],
         [1, 1, 3, 2]])]

In [143]:
matrix_x = np.matlib.mat([[4, 1, 5, 4],
         [5, 3, 3, 3],
         [5, 3, 1, 5],
         [5, 4, 2, 1]])
                  
matrix_y = np.matlib.mat([[4, 2, 4, 4],
         [5, 4, 2, 2],
         [1, 1, 2, 3],
         [1, 1, 3, 2]])

In [168]:
def matrix_multiplication(x,y):
    a_x = np.array(x)
    a_y = np.array(y)
    x_rows = len(a_x)
    x_columns = len(a_x[0])
    y_columns = len(a_y[0])
    y_rows = len(a_y)
    if y_rows != x_columns:
        print('Invalid matrix sizes')
        return
    product = np.zeros((x_rows, y_columns))
    for i in range(x_rows):
        for j in range(y_columns):
            total = 0
            for k in range(y_rows):
                total += a_x[i][k] * a_y[k][j]
            product[i][j] = total
    new_matrix = np.matlib.mat(product)
    print(new_matrix)
    
matrix_multiplication(matrix_x, matrix_y)

[[30. 21. 40. 41.]
 [41. 28. 41. 41.]
 [41. 28. 43. 39.]
 [43. 29. 35. 36.]]


\begin{equation}
\begin{bmatrix}
4 & 1 & 5 & 4 \\
5 & 3 & 3 & 3 \\
5 & 3 & 1 & 5 \\
5 & 4 & 2 & 1
\end{bmatrix}
\begin{bmatrix}
4 & 2 & 4 & 4 \\
5 & 4 & 2 & 2 \\
1 & 1 & 2 & 3 \\
1 & 1 & 3 & 2
\end{bmatrix}
\end{equation}



\begin{equation}
\begin{bmatrix}
4\cdot4 + 1\cdot5 + 5\cdot1 + 4\cdot1 & 4\cdot2 + 1\cdot4 + 5\cdot1 + 4\cdot1 & 
4\cdot4 + 1\cdot2 + 5\cdot2 + 4\cdot3 & 4\cdot4 + 1\cdot2 + 5\cdot3 + 4\cdot2 \\
5\cdot4 + 3\cdot5 + 3\cdot1 + 3\cdot1 & 5\cdot2 + 3\cdot4 + 3\cdot1 + 3\cdot1 & 
5\cdot4 + 3\cdot2 + 3\cdot2 + 3\cdot3 & 5\cdot4 + 3\cdot2 + 3\cdot3 + 3\cdot2 \\
5\cdot4 + 3\cdot5 + 1\cdot1 + 5\cdot1 & 5\cdot2 + 3\cdot4 + 1\cdot1 + 5\cdot1 &
5\cdot4 + 3\cdot2 + 1\cdot2 + 5\cdot3 & 5\cdot4 + 3\cdot2 + 1\cdot3 + 5\cdot2 \\
5\cdot4 + 4\cdot5 + 2\cdot1 + 1\cdot1 & 5\cdot2 + 4\cdot4 + 2\cdot1 + 1\cdot1 &
5\cdot4 + 4\cdot2 + 2\cdot2 + 1\cdot3 & 5\cdot4 + 4\cdot2 + 2\cdot3 + 1\cdot2
\end{bmatrix}
\end{equation}

\begin{equation}
\begin{bmatrix}
30 & 21 & 40 & 41 \\
41 & 28 & 41 & 41 \\
41 & 28 & 43 & 39 \\
43 & 29 & 35 & 36 
\end{bmatrix}
\end{equation}

In [24]:
print(matrix_x * matrix_y)

[[30 21 40 41]
 [41 28 41 41]
 [41 28 43 39]
 [43 29 35 36]]


Problem 2 Hadamard 

\begin{equation}
\begin{bmatrix}
4 & 1 & 5 & 4 \\
5 & 3 & 3 & 3 \\
5 & 3 & 1 & 5 \\
5 & 4 & 2 & 1
\end{bmatrix}
\odot
\begin{bmatrix}
4 & 2 & 4 & 4 \\
5 & 4 & 2 & 2 \\
1 & 1 & 2 & 3 \\
1 & 1 & 3 & 2
\end{bmatrix}
\end{equation}

\begin{equation}
\begin{bmatrix}
4\cdot4 & 1\cdot2 & 5\cdot4 & 4\cdot4 \\
5\cdot5 & 3\cdot4 & 3\cdot2 & 3\cdot2 \\
5\cdot1 & 3\cdot1 & 1\cdot2 & 5\cdot3 \\
5\cdot1 & 4\cdot1 & 2\cdot3 & 1\cdot2 
\end{bmatrix}
\end{equation}

\begin{equation}
\begin{bmatrix}
16 & 2 & 20 & 16 \\
25 & 12 & 6 & 6 \\
5 & 3 & 2 & 15 \\
5 & 4 & 6 & 2 
\end{bmatrix}
\end{equation}

In [133]:
def hadamard(x, y):
    a_x = np.array(x)
    a_y = np.array(y)
    if len(a_x) != len(a_y) or len(a_x[0]) != len(a_y[0]):
        print('Invalid matrix sizes')
        return
    l_h = []
    for i in range(len(a_y)):
        l_h.append([])
        for j in range(len(a_y[0])):
            l_h[i].append(a_x[i][j] * a_y[i][j])
    hadamard_matrix = np.matlib.mat(l_h)
    print(hadamard_matrix)
    
hadamard(matrix_x, matrix_y)

[[16  2 20 16]
 [25 12  6  6]
 [ 5  3  2 15]
 [ 5  4  6  2]]


Problem 2 Kronecker

\begin{equation}
\begin{bmatrix}
4 & 1 & 5 & 4 \\
5 & 3 & 3 & 3 \\
5 & 3 & 1 & 5 \\
5 & 4 & 2 & 1
\end{bmatrix}
\otimes
\begin{bmatrix}
4 & 2 & 4 & 4 \\
5 & 4 & 2 & 2 \\
1 & 1 & 2 & 3 \\
1 & 1 & 3 & 2
\end{bmatrix}
\end{equation}

In [134]:
def kronecker(x, y):
    a_x = np.array(x)
    a_y = np.array(y)
    x_rows = len(a_x)
    x_columns = len(a_x[0])
    y_rows = len(a_y)
    y_columns = len(a_y[0])
    l_k = np.zeros((x_rows * y_rows, x_columns * y_columns))
    for i in range(x_rows):
        for j in range(y_rows):
            for k in range(x_columns):
                for l in range(y_columns):
                    l_k[i*y_columns+j][y_columns*k+l] = a_x[i][k] * a_y[j][l]
               
    kronecker_matrix = np.matlib.mat(l_k)
    print(kronecker_matrix)
    
kronecker(matrix_x, matrix_y)

[[16.  8. 16. 16.  4.  2.  4.  4. 20. 10. 20. 20. 16.  8. 16. 16.]
 [20. 16.  8.  8.  5.  4.  2.  2. 25. 20. 10. 10. 20. 16.  8.  8.]
 [ 4.  4.  8. 12.  1.  1.  2.  3.  5.  5. 10. 15.  4.  4.  8. 12.]
 [ 4.  4. 12.  8.  1.  1.  3.  2.  5.  5. 15. 10.  4.  4. 12.  8.]
 [20. 10. 20. 20. 12.  6. 12. 12. 12.  6. 12. 12. 12.  6. 12. 12.]
 [25. 20. 10. 10. 15. 12.  6.  6. 15. 12.  6.  6. 15. 12.  6.  6.]
 [ 5.  5. 10. 15.  3.  3.  6.  9.  3.  3.  6.  9.  3.  3.  6.  9.]
 [ 5.  5. 15. 10.  3.  3.  9.  6.  3.  3.  9.  6.  3.  3.  9.  6.]
 [20. 10. 20. 20. 12.  6. 12. 12.  4.  2.  4.  4. 20. 10. 20. 20.]
 [25. 20. 10. 10. 15. 12.  6.  6.  5.  4.  2.  2. 25. 20. 10. 10.]
 [ 5.  5. 10. 15.  3.  3.  6.  9.  1.  1.  2.  3.  5.  5. 10. 15.]
 [ 5.  5. 15. 10.  3.  3.  9.  6.  1.  1.  3.  2.  5.  5. 15. 10.]
 [20. 10. 20. 20. 16.  8. 16. 16.  8.  4.  8.  8.  4.  2.  4.  4.]
 [25. 20. 10. 10. 20. 16.  8.  8. 10.  8.  4.  4.  5.  4.  2.  2.]
 [ 5.  5. 10. 15.  4.  4.  8. 12.  2.  2.  4.  6.  1.  1.  2. 

In [174]:
x = np.matlib.mat([[1,-4,7],[-2,3,3]])

In [175]:
y = np.matlib.mat([[8,-9,-6,5],[1,-3,-4,7],[2,8,-8,-3],[1,2,-5,-1]])

In [165]:
r = np.matlib.mat([[8,-9,-6,5],[1,-3,-4,7],[2,8,-8,-3]])

In [137]:
print(x)
print(y)

[[ 1 -4  7]
 [-2  3  3]]
[[ 8 -9 -6  5]
 [ 1 -3 -4  7]
 [ 2  8 -8 -3]
 [ 1  2 -5 -1]]


In [138]:
kronecker(x, y)

[[  8.  -9.  -6.   5. -32.  36.  24. -20.  56. -63. -42.  35.]
 [  1.  -3.  -4.   7.  -4.  12.  16. -28.   7. -21. -28.  49.]
 [  2.   8.  -8.  -3.  -8. -32.  32.  12.  14.  56. -56. -21.]
 [  1.   2.  -5.  -1.  -4.  -8.  20.   4.   7.  14. -35.  -7.]
 [-16.  18.  12. -10.  24. -27. -18.  15.  24. -27. -18.  15.]
 [ -2.   6.   8. -14.   3.  -9. -12.  21.   3.  -9. -12.  21.]
 [ -4. -16.  16.   6.   6.  24. -24.  -9.   6.  24. -24.  -9.]
 [ -2.  -4.  10.   2.   3.   6. -15.  -3.   3.   6. -15.  -3.]]


In [139]:
w = np.matlib.mat([[1,2],[3,4]])

In [140]:
v = np.matlib.mat([[0,5],[6,7]])

In [141]:
hadamard(w,v)

[[ 0 10]
 [18 28]]


In [142]:
hadamard(x,y)

Invalid matrix sizes


In [169]:
matrix_multiplication(x,y)

Invalid matrix sizes


In [170]:
matrix_multiplication(x,r)

[[ 18.  59. -46. -44.]
 [ -7.  33. -24.   2.]]


Problem 2: SVD

In [171]:
def determinant_r2(matrix):
    arr = np.array(matrix)
    return arr[0][0] * arr[1][1] - arr[0][1] * arr[1][0]
            

In [176]:
p = np.matlib.mat([[2,4],[1,3]])
q = np.matlib.mat([[2,4],[3,6]])
print(determinant_r2(p))
print(determinant_r2(q))

2
0


In [190]:
def determinant_r3(matrix):
    arr = np.array(matrix)
    total = 0
    for x in range(3):
        i = 0
        if x == 0:
            i = 1
        j = 2
        if x == 2:
            j = 1
        total += ((-1) ** x) * arr[0][x] * determinant_r2(np.matlib.matrix([[arr[1][i],arr[1][j]],[arr[2][i],arr[2][j]]]))
    return total   
        

In [191]:
z = np.matlib.mat([[1,2,-1],[5,3,4],[-2,0,1]])
print(determinant_r3(z))

-29


In [196]:
def determinant_r4(matrix):
    arr = np.array(matrix)
    total = 0
    for x in range(4):
        i = 0
        if x == 0:
            i = 1
        j = 2
        if x > 1:
            j = 1
        k = 3
        if x == 3:
            k = 2
        matrix_r3 = np.matlib.mat([[arr[1][i],arr[1][j],arr[1][k]],[arr[2][i],arr[2][j],arr[2][k]],[arr[3][i],arr[3][j],arr[3][k]]])
        total += ((-1) ** x) * arr[0][x] * determinant_r3(matrix_r3)
    return total

In [198]:
c = np.matlib.mat([[1,2,-1,1],[-1,0,2,-2],[3,-1,1,1],[2,0,-1,2]])
print(determinant_r4(c))

3


In [202]:
import numpy.linalg

d = np.matlib.mat([[1,1,1],[0,3,3],[-2,1,1]])
np.linalg.eig(d)

(array([-4.4408921e-16,  2.0000000e+00,  3.0000000e+00]),
 matrix([[ 6.63989126e-17,  5.34522484e-01,  4.47213595e-01],
         [ 7.07106781e-01,  8.01783726e-01,  8.94427191e-01],
         [-7.07106781e-01, -2.67261242e-01,  4.29987528e-16]]))

In [230]:
def svd(matrix):
    matrix_transpose = np.matrix.transpose(matrix)
    mmt = matrix * matrix_transpose
    mmt_values, mmt_vectors = np.linalg.eig(mmt)
    mtm = matrix_transpose * matrix
    mtm_values, mtm_vectors = np.linalg.eig(mtm)
    m_len = len(matrix)
    e = np.zeros(m_len)
    print(e)
    for x in range(m_len):
        e[x] = np.sqrt(mtm_values[x])
    return mmt_vectors, np.matlib.mat(e), mtm_vectors
    
    
u, e, v = svd(w)
print(f'u: {u}')
print(f'e: {e}')
print(f'v: {v}')

[0. 0.]
u: [[-0.9145143  -0.40455358]
 [ 0.40455358 -0.9145143 ]]
e: [[0.36596619 5.4649857 ]]
v: [[-0.81741556 -0.57604844]
 [ 0.57604844 -0.81741556]]


In [219]:
print(np.linalg.svd(w))

(matrix([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), matrix([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))


In [ ]:
I am a little crispy at this 