In [15]:
import numpy as np

In [16]:
b = np.array([1,2,3,4,5,6,7,8,9,0])


In [17]:
b[[0,5,-1]]

array([1, 6, 0])

In [18]:
b = np.array(['a'])
b.dtype


dtype('<U1')

In [19]:
mat = np.array([
    [1, 2],
    [3, 4]
])
print(mat.shape)
print(mat.ndim)
print(mat.size)


(2, 2)
2
4


In [23]:
b = mat[:, 1:]
print(b)
print(b.transpose())

[[2]
 [4]]
[[2 4]]


In [24]:
print(b @ b.transpose())

[[ 4  8]
 [ 8 16]]


In [25]:
print(b.transpose() @ b)

[[20]]


In [26]:
mat

array([[1, 2],
       [3, 4]])

In [31]:
(mat[:, 1:]).sum()

6

In [29]:
mat.sum()


10

In [32]:
mat[:]

array([[1, 2],
       [3, 4]])

In [33]:
v = np.arange(5) + 1

In [34]:
v

array([1, 2, 3, 4, 5])

In [35]:
v += np.arange(5) + 5
v

array([ 6,  8, 10, 12, 14])

In [36]:
v

array([ 6,  8, 10, 12, 14])

In [40]:
v[[True, False, True, False, False]]

array([ 6, 10])

In [41]:
w = np.array([v,v])

In [42]:
w

array([[ 6,  8, 10, 12, 14],
       [ 6,  8, 10, 12, 14]])

In [43]:
w[1] = w[1] + 5

In [44]:
w

array([[ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19]])

In [45]:
c = w[[True,False,False,True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4