In [10]:
import numpy as np


In [60]:
arr = np.arange(30).reshape((6,5)) + 1

In [61]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr[2:4, :2]

array([[11, 12],
       [16, 17]])

In [65]:
arr[((arr < 21) & (arr % 6 == 2))]

array([ 2,  8, 14, 20])

In [67]:
arr[[0,-2,-1], -2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [70]:
z = np.array([[29,97,32,100,45],[15,88,5,75,22]])

In [71]:
z[z<50]

array([29, 32, 45, 15,  5, 22])